function randomMovie() {
    var moviesArray = [
        "Butch Cassidy and the Sundance Kid",
        "The Dirty Dozen",
        "Point Break",
        "Three Billboards",
        "The Martian",
        "The Cabin in the Woods",
        "Sunset Blvd.",
        "All About Eve",
        "The African Queen",
        "One Flew Over the Cuckoo's Nest",
        "The Grapes of Wrath",
        "Dr Strangelove",
        "Bonnie and Clyde",
        "Mr Smith Goes to Washington",
        "The Treasure of the Sierra Madre",
        "Annie Hall",
        "High Noon",
        "It Happened One Night",
        "The Best Years of Our Lives",
        "Double Indemnity",
        "The Best Years of Our Lives",
        "Dr Zhivago",
        "Rear Window",
        "The Birth of a Nation",
        "The Philadelphia Story",
        "From Here to Eternity",
        "All Quiet on the Western Front",
        "The Third Man",
        "Vertigo",
        "Stagecoach",
        "Close Encounters of the Third Kind",
        "Network",
        "The Manchurian Candidate",
        "An American in Paris",
        "Shane",
        "Wuthering Heights",
        "The Gold Rush",
        "City Lights",
        "The Wild Bunch",
        "Modern Times",
        "Giant",
        "Duck Soup",
        "Mutiny on the Bounty",
        "Easy Rider",
        "Patton",
        "The Jazz Singer",
        "A Place in the Sun",
        "The Apartment",
        "The Searchers",
        "Bringing Up Baby",
        "Guess Who's Comign to Dinner",
        "Yankee Doodle Dandy",
        "The Tribe (2014)",
        "Lincoln (2012)",
        "Personal Shopper",
        "Black Coal, Thin Ice",
        "Hereditary (2018)",
        "Amour (2012)",
        "Elena (2011)",
        "Call Me By Your Name",
        "First Reformed",
        "Zama",
        "45 Years",
        "We Are the Best",
        "Tangerine",
        "You Were Never Really Here",
        "The Lobster",
        "No (2012)",
        "Meek's Cutoff",
        "Spring Breakers",
        "Cold War",
        "Uncle Boonmee Who Can Recall His Past Lives",
        "Selma",
        "The Act of Killing",
        "Dunkirk",
        "Lady Bird",
        "Burning (2018)",
        "The Irishman",
        "Anomalisa",
        "Under the Skin",
        "12 Years a Slave",
        "Inside Llewyln Davis",
        "A Separation (2011)",
        "Phantom Thread",
        "Carol",
        "Roma",
        "The Master",
        "Boyhood",
        "Holy Motors",
        "The Social Network",
        "Mystic River",
        "Mulholland Drive",
        "Children of Men",
        "25th Hour",
        "4 Months, 3 Weeks, and 2 Days",
        "Old Joy",
        "Hunger (2008)",
        "You Can Count On Me",
        "I'm Not There",
        "Mudbound",
        "Son of Saul",
        "Stories We Tell",
        "The Fog of War",
        "1917",
        "Marriage Story",
        "The Favourite",
        "BlackkKlansman",
        "Darkest Hour",
        "Phantom Thread",
        "The Post",
        "La La Land",
        "Arrival (2017)",
        "Lion (2017)",
        "Hell or High Water (2017)",
        "Hidden Figures",
        "Hacksaw Ridge",
        "Manchester by the Sea",
        "Fences (2017)",
        "Bridge of Spies",
        "The Revenant",
        "Room",
        "Brooklyn",
        "Whiplash",
        "The Theory of Everything",
        "Philomena",
        "Nebraska",
        "Captain Phillips",
        "The Wolf of Wall Street",
        "Life of Pi",
        "The Artist",
        "Extremely Loud and Incredibly Close",
        "War Horse",
        "Hugo",
        "The Help",
        "Precious",
        "An Education",
        "The Mummy",
        "Ready or Not",
        "Bad Times at the El Royale",
        "The Silent Partner",
        "A Hologram for the King",
        "The Towering Inferno",
        "Victory (1981)",
        "McCabe and Mrs. Miller (1971)",
        "True Romance",
        "Used Cars",
        "The Prophecy",
        "Dark City",
        "Motherless Brooklyn",
        "The Thing (1982)"
    ];
    var movieTonight = moviesArray[Math.floor(Math.random() * moviesArray.length)];
    console.log(moviesArray.length);
    console.log(movieTonight);
}
randomMovie();