function randomMovie() {
    var moviesArray = [
        "Butch Cassidy and the Sundance Kid",
        "The Dirty Dozen",
        "Point Break",
        "Three Billboards",
        "The Martian",
        "The Cabin in the Woods",
        "Sunset Blvd.",
        "All About Eve",
        "The African Queen",
        "The Grapes of Wrath",
        "Dr Strangelove",
        "Bonnie and Clyde",
        "Mr Smith Goes to Washington",
        "The Treasure of the Sierra Madre",
        "Annie Hall",
        "High Noon",
        "It Happened One Night",
        "The Best Years of Our Lives",
        "Double Indemnity",
        "The Best Years of Our Lives",
        "Dr Zhivago",
        "Rear Window",
        "The Birth of a Nation",
        "The Philadelphia Story",
        "From Here to Eternity",
        "All Quiet on the Western Front",
        "The Third Man",
        "Stagecoach",
        "Close Encounters of the Third Kind",
        "The Manchurian Candidate",
        "An American in Paris",
        "Shane",
        "The Gold Rush",
        "City Lights",
        "The Wild Bunch",
        "Modern Times",
        "Giant",
        "Duck Soup",
        "Easy Rider",
        "Patton",
        "The Jazz Singer",
        "A Place in the Sun",
        "The Apartment",
        "Bringing Up Baby",
        "Guess Who's Comign to Dinner",
        "Yankee Doodle Dandy",
        "The Tribe (2014)",
        "Lincoln (2012)",
        "Personal Shopper",
        "Black Coal, Thin Ice",
        "Hereditary (2018)",
        "Amour (2012)",
        "Elena (2011)",
        "Call Me By Your Name",
        "First Reformed",
        "Zama",
        "45 Years",
        "We Are the Best",
        "Tangerine",
        "You Were Never Really Here",
        "No (2012)",
        "Meek's Cutoff",
        "Spring Breakers",
        "Cold War",
        "Uncle Boonmee Who Can Recall His Past Lives",
        "Selma",
        "The Act of Killing",
        "Dunkirk",
        "Burning (2018)",
        "Anomalisa",
        "Under the Skin",
        "12 Years a Slave",
        "Inside Llewyln Davis",
        "A Separation (2011)",
        "Phantom Thread",
        "Roma",
        "Boyhood",
        "Holy Motors",
        "Mystic River",
        "Mulholland Drive",
        "Children of Men",
        "25th Hour",
        "4 Months, 3 Weeks, and 2 Days",
        "Old Joy",
        "Hunger (2008)",
        "You Can Count On Me",
        "I'm Not There",
        "Mudbound",
        "Son of Saul",
        "Stories We Tell",
        "The Fog of War",
        "1917",
        "Marriage Story",
        "The Favourite",
        "BlackkKlansman",
        "Darkest Hour",
        "Phantom Thread",
        "The Post",
        "La La Land",
        "Arrival (2017)",
        "Lion (2017)",
        "Hell or High Water (2017)",
        "Hidden Figures",
        "Hacksaw Ridge",
        "Fences (2017)",
        "Bridge of Spies",
        "The Revenant",
        "Brooklyn",
        "Whiplash",
        "The Theory of Everything",
        "Philomena",
        "Nebraska",
        "Captain Phillips",
        "The Wolf of Wall Street",
        "Life of Pi",
        "The Artist",
        "Extremely Loud and Incredibly Close",
        "War Horse",
        "Precious",
        "An Education",
        "Bad Times at the El Royale",
        "The Silent Partner",
        "A Hologram for the King",
        "The Towering Inferno",
        "Victory (1981)",
        "McCabe and Mrs. Miller (1971)",
        "True Romance",
        "Used Cars",
        "The Prophecy",
        "Dark City",
        "Motherless Brooklyn",
        "The Thing (1982)",
        "Kingdom of Heaven (Directors Cut)",
        "Butterfly Effect  (Directors Cut)",
        "John Carter",
        "The Gift",
        "Running on Empty",
        "Lone Star",
        "Stuart: A Life Backward",
        "The Man From UNCLE",
        "The Fall",
        "Her",
        "A Most Violent Year",
        "Once AND Begin Again AND Sing Street",
        "Big Nothing",
        "Deep Cover",
        "Repo Man",
        "Boondock Saints",
        "The Next Three Days",
        "Taxi Driver",
        "King of Comedy",
        "Scarface",
        "Rush (2013)",
        "The Conversation",
        "American Made",
        "Warrior (2011)",
        "Whiplash",
        "Steve Jobs",
        "The Nice Guys",
        "Honey Boy",
        "The Lighthouse",
        "Nightcrawler",
        "The Grand Budapest Hotel",
        "12 Angry Men",
        "Rope",
        "Escape From New York",
        "St Vincent",
        "The Sting",
        "Requiem for a Dream",
        "Rear Window",
        "Strangers on a Train"
    ];
    var movieTonight = moviesArray[Math.floor(Math.random() * moviesArray.length)];
    console.log(moviesArray.length);
    console.log(movieTonight);
}
randomMovie();