function randomMovie() {
    var moviesArray = [
        "The Shawshank Redemption",
        "Cit of God",
        "12 Angry Men",
        "Bladerunner",
        "A Clockwork Orange",
        "The Deer Hunter",
        "Casablanca",
        "The Rocky Horror Picture Show",
        "Fight Club",
        "Snatch",
        "Old Boy",
        "Leon: The Professional",
        "Scarface",
        "Moonlight",
        "The Matrix",
        "Apocalypse Now",
        "The Grand Budapest Hotel",
        "Monty Python's The Life of Brian",
        "In Bruges",
        "3 Idiots",
        "The Notebook",
        "Dirty Dancing",
        "Schindler's List",
        "Breakfast at Tiffany's",
        "Shaun of the Dead",
        "The Silence of the Lambs",
        "The Shining",
        "Alien",
        "Memento",
        "Se7en",
        "Halloween",
        "Jaws",
        "The Evil Dead",
        "Airplane",
        "Lawrence of Arabia",
        "Drive",
        "Rosemary's Baby",
        "Mary & Max",
        "The Terminator",
        "The Green Mile",
        "This is Spinal Tap",
        "American Psycho",
        "Citizen Cane",
        "The Intouchables",
        "American History X",
        "Seven Samurai",
        "The Good, the Bad, and the Ugly",
        "Brokeback Mountain",
        "The Prestige",
        "Titanic",
        "Her",
        "Boyz n the Hood",
        "Four Weddings and a Funeral",
        "Little Miss Sunshine",
        "Trainspotting",
        "The Departed",
        "Saving Private Ryan",
        "No Country For Old Men",
        "The Pianist",
        "Dr. Strangelove",
        "Lagaan",
        "Baahubali",
        "Psycho",
        "Vertigo",
        "Amadeus",
        "Enter the Dragon",
        "Gangs of New York",
        "The Usual Suspects",
        "Good Will Hunting",
        "Heat",
        "Dead Poet's Society",
        "Clueless",
        "Little Women"
    ];
    var movieTonight = moviesArray[Math.floor(Math.random() * moviesArray.length)];
    console.log(moviesArray.length);
    console.log(movieTonight);
}
randomMovie();